#  command: ansible-playbook -i inventory.yml lab_ansible.yml --vault-password-file group_vars/all/ansible_vault_password.txt
---
- name: Configure system
  hosts: exploit_dev_ubuntu16  # Use the target host
  strategy: free
  become: true
  vars_files:
    - secrets.yml

  tasks:
    - name: Include multiple roles
      ansible.builtin.include_role:
        name: "{{ role_name }}"
        apply:
          become: yes
      loop:
        - package_installer
      loop_control:
        loop_var: role_name