---
- name: Configure system
  hosts: all
  strategy: free
  become: true
  vars_files:
    - secrets.yml

  tasks:
    - name: Include multiple roles
      ansible.builtin.include_role:
        name: "{{ role_name }}"
        apply:
          become: yes
      loop:
        - ubuntu_admin
      loop_control:
        loop_var: role_name