---
# Include multiple task files in a loop
- name: Include the custom tasks
  ansible.builtin.include_tasks: "{{ task_file }}"
  loop:
    - install_packages.yml
    - clean_packages.yml
    # - update_packages.yml
  loop_control:
    loop_var: task_file
