---
# tasks file for basic
- name: install essential packages
  package:
    name:
      #      - tree
      #      - lolcat
      #      - tig
      #      - ansible-lint
      #      - font-manager
      #      - liblzma-dev
      #      - cmake
      #      - sshpass
      - sl
    state: present
    update_cache: yes
    force: yes

- name: remove useless packages from the cache
  apt:
    autoclean: yes

- name: remove dependencies that are no longer required
  apt:
    autoremove: yes
